# Generated by Django 6.0.7 on 2026-07-19 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Compte bancaire')], max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('orange_money', 'Orange Money')], max_length=20, verbose_name='opérateur')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='numéro mobile money')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='banque')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='numéro de compte')),
                ('account_holder', models.CharField(blank=True, max_length=150, verbose_name='titulaire du compte')),
                ('is_default', models.BooleanField(default=False, verbose_name='par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moyen de paiement',
                'verbose_name_plural': 'moyens de paiement',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
