# Generated by Django 6.0.7 on 2026-07-20 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Recharge'), ('ride', 'Paiement de course'), ('refund', 'Remboursement'), ('bonus', 'Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('provider', models.CharField(blank=True, choices=[('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('orange_money', 'Orange Money'), ('cash', 'Espèces')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction portefeuille',
                'verbose_name_plural': 'transactions portefeuille',
                'ordering': ['-created_at'],
            },
        ),
    ]
