# Generated by Django 6.0.7 on 2026-07-13 00:34

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('role', models.CharField(choices=[('client', 'Client'), ('motard', 'Motard'), ('owner', 'Propriétaire de motos'), ('operator', 'Opérateur')], default='client', max_length=20, verbose_name='rôle')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MotardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='numéro de permis')),
                ('id_card_number', models.CharField(blank=True, max_length=50, verbose_name="numéro pièce d'identité")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='motards/photos/', verbose_name='photo de profil')),
                ('subscription_status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu')], default='expired', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_available', models.BooleanField(default=False, verbose_name='disponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motard_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil motard',
                'verbose_name_plural': 'profils motards',
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name="nom de l'entreprise")),
                ('id_card_number', models.CharField(blank=True, max_length=50, verbose_name="numéro pièce d'identité")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil propriétaire',
                'verbose_name_plural': 'profils propriétaires',
            },
        ),
    ]
