# Generated by Django 6.0.7 on 2026-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motardprofile',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Actif'), ('trial', 'En essai'), ('expired', 'Expiré'), ('suspended', 'Suspendu')], default='expired', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('motard', 'Motard'), ('owner', 'Propriétaire de motos'), ('fleet_manager', 'Gérant de flotte'), ('operator', 'Opérateur')], default='client', max_length=20, verbose_name='rôle'),
        ),
    ]
