# Generated by Django 6.0.7 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_motardprofile_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motardprofile',
            name='application_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut du dossier'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='avenue',
            field=models.CharField(blank=True, max_length=150, verbose_name='avenue / rue'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='commune / secteur'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='date_expiration_piece',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration de la pièce"),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='numero_maison',
            field=models.CharField(blank=True, max_length=20, verbose_name='numéro de la maison'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='permis_conduire_photo',
            field=models.FileField(blank=True, null=True, upload_to='motards/permis/', verbose_name='permis de conduire (recto-verso)'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='photo_piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='motards/pieces_identite/', verbose_name="photo/scan de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('kinshasa', 'Kinshasa'), ('kongo_central', 'Kongo-Central'), ('kwango', 'Kwango'), ('kwilu', 'Kwilu'), ('mai_ndombe', 'Mai-Ndombe'), ('kasai', 'Kasaï'), ('kasai_central', 'Kasaï-Central'), ('kasai_oriental', 'Kasaï-Oriental'), ('lomami', 'Lomami'), ('sankuru', 'Sankuru'), ('maniema', 'Maniema'), ('sud_kivu', 'Sud-Kivu'), ('nord_kivu', 'Nord-Kivu'), ('ituri', 'Ituri'), ('haut_uele', 'Haut-Uele'), ('bas_uele', 'Bas-Uele'), ('tshopo', 'Tshopo'), ('tshuapa', 'Tshuapa'), ('equateur', 'Équateur'), ('sud_ubangi', 'Sud-Ubangi'), ('nord_ubangi', 'Nord-Ubangi'), ('mongala', 'Mongala'), ('tanganyika', 'Tanganyika'), ('haut_lomami', 'Haut-Lomami'), ('lualaba', 'Lualaba'), ('haut_katanga', 'Haut-Katanga')], max_length=30, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='reference_adresse',
            field=models.CharField(blank=True, max_length=200, verbose_name='référence / point de repère'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe'),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('CARTE_ELECTEUR', "Carte d'électeur"), ('CARTE_NATIONALE', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('PERMIS_CONDUIRE', 'Permis de conduire'), ('LIVRET_TRAVAIL', 'Livret de travail'), ('AUTRE', 'Autre document officiel')], max_length=20, verbose_name="type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='motardprofile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville / territoire'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='post-nom'),
        ),
    ]
