# Generated by Django 6.0.7 on 2026-07-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoloc', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='rides.ride'),
        ),
    ]
