# Generated by Django 6.0.7 on 2026-07-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoloc', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['user', '-recorded_at'], name='geoloc_loca_user_id_c80b39_idx'),
        ),
    ]
