# Generated by Django 6.0.7 on 2026-07-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('owner_fleet', "Flotte d'un propriétaire (gérance)"), ('platform_fleet', 'Flotte Go-Mboka (allocation)')], max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name="plaque d'immatriculation")),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='marque')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='modèle')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Assignée'), ('maintenance', 'En maintenance'), ('retired', 'Retirée')], default='available', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission Go-Mboka prélevée sur les revenus générés par cette moto.', max_digits=5, verbose_name='taux de commission (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
    ]
