# Generated by Django 6.0.7 on 2026-07-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='assigned_motard',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'motard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_motorcycle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorcycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleetremittance',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='fleet.motorcycle'),
        ),
    ]
