# Generated by Django 6.0.7 on 2026-07-14 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='model_name',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'acquisition"),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='numéro de châssis/VIN'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='couleur'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID du tracker (IMEI)'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='fleet_manager',
            field=models.ForeignKey(blank=True, help_text='Gérant Go-Mboka en charge du suivi quotidien de cette moto (gérance et allocation).', limit_choices_to={'role': 'fleet_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_motorcycles', to=settings.AUTH_USER_MODEL, verbose_name='gérant de flotte'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='general_condition',
            field=models.IntegerField(default=10, verbose_name='état général (/10)'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='model_style',
            field=models.CharField(blank=True, max_length=100, verbose_name='style/modèle'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='ownership_type',
            field=models.CharField(choices=[('owner_fleet', "Flotte d'un propriétaire (gérance)"), ('platform_fleet', 'Flotte Go-Mboka (allocation)'), ('self_owned', 'Propriété du motard (abonnement)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('rental', 'Location Simple (Rental)'), ('hire_purchase', 'Location-Vente (Hire Purchase)')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire')], max_length=20)),
                ('periodic_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant périodique')),
                ('target_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='somme totale pour propriété')),
                ('amount_already_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant déjà versé')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='fleet.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='MotardTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_rides_required', models.PositiveIntegerField(default=0, verbose_name='courses min. requises')),
                ('min_rating_required', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note min. requise')),
                ('result', models.CharField(choices=[('pending', 'En cours'), ('validated', 'Validé'), ('rejected', 'Refusé'), ('extended', 'Prolongé')], default='pending', max_length=20)),
                ('final_notes', models.TextField(blank=True, verbose_name='observations finales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to=settings.AUTH_USER_MODEL)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_periods', to='fleet.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='TrialDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('return_time', models.TimeField(verbose_name='heure de retour')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='somme versée')),
                ('is_payment_complete', models.BooleanField(default=True, verbose_name='versement complet')),
                ('motard_explanation', models.TextField(blank=True, verbose_name='explications / plaintes')),
                ('bike_condition_score', models.PositiveIntegerField(default=10, verbose_name='état de la moto (/10)')),
                ('manager_notes', models.TextField(blank=True, verbose_name='notes du gérant')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='fleet.motardtrial')),
            ],
            options={
                'unique_together': {('trial', 'date')},
            },
        ),
    ]
